name = "portelo"
main = "src/worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./pages"

[[d1_databases]]
binding = "DB"
database_name = "portelo-db"
database_id = "a8c06eee-4a69-423b-8c07-01cdeb8ef9bb"

[[r2_buckets]]
binding = "BILLS_BUCKET"
bucket_name = "portelo-bills"

[vars]
ENVIRONMENT = "development"
