INSERT OR IGNORE INTO residents (id, building_id, apartment_ref, pin_hash, active) VALUES ('res_ch_f14c48eb', 'ch', '1', '$2a$10$eA8knlMGlLIGJSElt0NsCuPIOaxEGRDg/1aGRztRQ1zYSNAfvB5Vm', 1);
INSERT OR IGNORE INTO residents (id, building_id, apartment_ref, pin_hash, active) VALUES ('res_ch_306e990e', 'ch', '1A', '$2a$10$eA8knlMGlLIGJSElt0NsCuPIOaxEGRDg/1aGRztRQ1zYSNAfvB5Vm', 1);
INSERT OR IGNORE INTO residents (id, building_id, apartment_ref, pin_hash, active) VALUES ('res_ch_ee81d1bc', 'ch', '2', '$2a$10$eA8knlMGlLIGJSElt0NsCuPIOaxEGRDg/1aGRztRQ1zYSNAfvB5Vm', 1);
INSERT OR IGNORE INTO residents (id, building_id, apartment_ref, pin_hash, active) VALUES ('res_ch_33fe4aad', 'ch', '2A', '$2a$10$eA8knlMGlLIGJSElt0NsCuPIOaxEGRDg/1aGRztRQ1zYSNAfvB5Vm', 1);
INSERT OR IGNORE INTO residents (id, building_id, apartment_ref, pin_hash, active) VALUES ('res_ch_7e2838f2', 'ch', '3', '$2a$10$eA8knlMGlLIGJSElt0NsCuPIOaxEGRDg/1aGRztRQ1zYSNAfvB5Vm', 1);
INSERT OR IGNORE INTO residents (id, building_id, apartment_ref, pin_hash, active) VALUES ('res_ch_d721a7b0', 'ch', '3A', '$2a$10$eA8knlMGlLIGJSElt0NsCuPIOaxEGRDg/1aGRztRQ1zYSNAfvB5Vm', 1);
INSERT OR IGNORE INTO residents (id, building_id, apartment_ref, pin_hash, active) VALUES ('res_ch_02600b6f', 'ch', '4', '$2a$10$eA8knlMGlLIGJSElt0NsCuPIOaxEGRDg/1aGRztRQ1zYSNAfvB5Vm', 1);
INSERT OR IGNORE INTO residents (id, building_id, apartment_ref, pin_hash, active) VALUES ('res_ch_9d7be864', 'ch', '4A', '$2a$10$eA8knlMGlLIGJSElt0NsCuPIOaxEGRDg/1aGRztRQ1zYSNAfvB5Vm', 1);
INSERT OR IGNORE INTO residents (id, building_id, apartment_ref, pin_hash, active) VALUES ('res_ch_53df8c04', 'ch', '5', '$2a$10$eA8knlMGlLIGJSElt0NsCuPIOaxEGRDg/1aGRztRQ1zYSNAfvB5Vm', 1);
INSERT OR IGNORE INTO residents (id, building_id, apartment_ref, pin_hash, active) VALUES ('res_ch_f631c726', 'ch', '6', '$2a$10$eA8knlMGlLIGJSElt0NsCuPIOaxEGRDg/1aGRztRQ1zYSNAfvB5Vm', 1);
INSERT OR IGNORE INTO residents (id, building_id, apartment_ref, pin_hash, active) VALUES ('res_ch_2c230df4', 'ch', '7', '$2a$10$eA8knlMGlLIGJSElt0NsCuPIOaxEGRDg/1aGRztRQ1zYSNAfvB5Vm', 1);
INSERT OR IGNORE INTO residents (id, building_id, apartment_ref, pin_hash, active) VALUES ('res_ch_49f8a07b', 'ch', '8', '$2a$10$eA8knlMGlLIGJSElt0NsCuPIOaxEGRDg/1aGRztRQ1zYSNAfvB5Vm', 1);
INSERT OR IGNORE INTO residents (id, building_id, apartment_ref, pin_hash, active) VALUES ('res_ch_26edc7c6', 'ch', '9', '$2a$10$eA8knlMGlLIGJSElt0NsCuPIOaxEGRDg/1aGRztRQ1zYSNAfvB5Vm', 1);
INSERT OR IGNORE INTO residents (id, building_id, apartment_ref, pin_hash, active) VALUES ('res_ch_28854201', 'ch', '10', '$2a$10$eA8knlMGlLIGJSElt0NsCuPIOaxEGRDg/1aGRztRQ1zYSNAfvB5Vm', 1);
INSERT OR IGNORE INTO residents (id, building_id, apartment_ref, pin_hash, active) VALUES ('res_ch_799fd58d', 'ch', '11', '$2a$10$eA8knlMGlLIGJSElt0NsCuPIOaxEGRDg/1aGRztRQ1zYSNAfvB5Vm', 1);
INSERT OR IGNORE INTO residents (id, building_id, apartment_ref, pin_hash, active) VALUES ('res_ch_bc637757', 'ch', '12', '$2a$10$eA8knlMGlLIGJSElt0NsCuPIOaxEGRDg/1aGRztRQ1zYSNAfvB5Vm', 1);
INSERT OR IGNORE INTO residents (id, building_id, apartment_ref, pin_hash, active) VALUES ('res_ch_04fb97ff', 'ch', '13', '$2a$10$eA8knlMGlLIGJSElt0NsCuPIOaxEGRDg/1aGRztRQ1zYSNAfvB5Vm', 1);
INSERT OR IGNORE INTO residents (id, building_id, apartment_ref, pin_hash, active) VALUES ('res_ch_c0bd980d', 'ch', '14', '$2a$10$eA8knlMGlLIGJSElt0NsCuPIOaxEGRDg/1aGRztRQ1zYSNAfvB5Vm', 1);
INSERT OR IGNORE INTO residents (id, building_id, apartment_ref, pin_hash, active) VALUES ('res_ch_aaa8e8d5', 'ch', '15', '$2a$10$eA8knlMGlLIGJSElt0NsCuPIOaxEGRDg/1aGRztRQ1zYSNAfvB5Vm', 1);
INSERT OR IGNORE INTO residents (id, building_id, apartment_ref, pin_hash, active) VALUES ('res_ch_441e2e16', 'ch', '16', '$2a$10$eA8knlMGlLIGJSElt0NsCuPIOaxEGRDg/1aGRztRQ1zYSNAfvB5Vm', 1);
INSERT OR IGNORE INTO residents (id, building_id, apartment_ref, pin_hash, active) VALUES ('res_ch_73eef46b', 'ch', '17', '$2a$10$eA8knlMGlLIGJSElt0NsCuPIOaxEGRDg/1aGRztRQ1zYSNAfvB5Vm', 1);
INSERT OR IGNORE INTO residents (id, building_id, apartment_ref, pin_hash, active) VALUES ('res_ch_8e08245f', 'ch', '18', '$2a$10$eA8knlMGlLIGJSElt0NsCuPIOaxEGRDg/1aGRztRQ1zYSNAfvB5Vm', 1);
INSERT OR IGNORE INTO residents (id, building_id, apartment_ref, pin_hash, active) VALUES ('res_ch_3a5a4713', 'ch', 'Lokal 3', '$2a$10$eA8knlMGlLIGJSElt0NsCuPIOaxEGRDg/1aGRztRQ1zYSNAfvB5Vm', 1);
INSERT OR IGNORE INTO residents (id, building_id, apartment_ref, pin_hash, active) VALUES ('res_ch_8f677399', 'ch', 'Lokal 1', '$2a$10$eA8knlMGlLIGJSElt0NsCuPIOaxEGRDg/1aGRztRQ1zYSNAfvB5Vm', 1);
INSERT OR IGNORE INTO residents (id, building_id, apartment_ref, pin_hash, active) VALUES ('res_ch_107fd6c6', 'ch', '5A', '$2a$10$eA8knlMGlLIGJSElt0NsCuPIOaxEGRDg/1aGRztRQ1zYSNAfvB5Vm', 1);
INSERT OR IGNORE INTO residents (id, building_id, apartment_ref, pin_hash, active) VALUES ('res_ch_644cd9ae', 'ch', '12A', '$2a$10$eA8knlMGlLIGJSElt0NsCuPIOaxEGRDg/1aGRztRQ1zYSNAfvB5Vm', 1);
INSERT OR IGNORE INTO residents (id, building_id, apartment_ref, pin_hash, active) VALUES ('res_ch_d61cdd24', 'ch', '13A', '$2a$10$eA8knlMGlLIGJSElt0NsCuPIOaxEGRDg/1aGRztRQ1zYSNAfvB5Vm', 1);
INSERT OR IGNORE INTO residents (id, building_id, apartment_ref, pin_hash, active) VALUES ('res_ch_73301843', 'ch', '14A', '$2a$10$eA8knlMGlLIGJSElt0NsCuPIOaxEGRDg/1aGRztRQ1zYSNAfvB5Vm', 1);
INSERT OR IGNORE INTO residents (id, building_id, apartment_ref, pin_hash, active) VALUES ('res_ch_87a44e35', 'ch', '15A', '$2a$10$eA8knlMGlLIGJSElt0NsCuPIOaxEGRDg/1aGRztRQ1zYSNAfvB5Vm', 1);
INSERT OR IGNORE INTO residents (id, building_id, apartment_ref, pin_hash, active) VALUES ('res_ch_7b364a5a', 'ch', 'Lokal 2', '$2a$10$eA8knlMGlLIGJSElt0NsCuPIOaxEGRDg/1aGRztRQ1zYSNAfvB5Vm', 1);
